---
- name: Download and install cfssl tools
  get_url:
    url: "{{ cfssl_package_url }}{{ item }}_linux-amd64"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    force: yes
  loop: "{{ cfssl_packages }}"

- name: Register cfssl version
  shell: |
    cfssl version
  register: cfssl_version_status

- name: Debug cfssl version
  debug:
    msg: "{{ cfssl_version_status.stdout_lines }}"