---
- name: Test playbook
  hosts: [ "all", ]
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - { name: "docker", role: "apps/k8s/docker", tags: "docker" }
    - { name: "test", role: "apps/k8s/etcd", tags: "test" }
