---
- name: Config /etc/systemd/system/postgres_exporter.service
  template:
    src: etc/systemd/system/postgres_exporter.service.j2
    dest: /etc/systemd/system/postgres_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: Daemon reload
  systemd:
    daemon_reload: yes

- name: Start postgres_exporter
  systemd:
    state: started
    daemon_reload: yes
    name: postgres_exporter
    enabled: yes

