---
- name: All import secrets playbook
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Include secrets file
      include_vars: secrets/secrets.yml

    - name: Debug secrets value
      debug:
        var: secrets_version

    - name: Debug env_name value
      debug:
        var: env_name