---
- name: Create dir /var/run/ansible
  ansible.builtin.file:
    path: /var/run/ansible
    state: directory

- name: Create end tag if run complete
  ansible.builtin.file:
    path: "/var/run/ansible/.{{ role_name | regex_replace('/', '.') }}.run"
    state: touch