---
- name: Start docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Stop docker
  systemd:
    state: stopped
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Reload docker
  systemd:
    state: reloaded
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Restart docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
    enabled: yes