---
- name: Install kernel package
  yum:
    name: "{{ base_kernel_url }}"
    state: latest

- name: Update config for kernel
  shell: |
    grub2-set-default 0
    grub2-mkconfig -o /boot/grub2/grub.cfg
  args:
    warn: no