---
- name: Yum install docker base packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ docker_base_packages }}"

- name: Start docker
  systemd:
    state: started
    daemon_reload: yes
    name: docker
    enabled: yes

- name: Register docker version
  shell: |
    docker version
  register: register_docker_version

- name: Debug docker version
  debug:
    msg: "{{ register_docker_version.stdout_lines }}"

# - name: Upgrade pip
#   pip:
#     name: pip
#     executable: pip3
#     state: latest

- name: Pip install docker compose
  pip:
    name: "{{ item }}"
    executable: pip3
  loop: "{{ docker_compose_base_packages }}"

- name: Register docker compose version
  shell: |
    docker-compose version
  register: register_docker_compose_version

- name: Debug docker compose version
  debug:
    msg: "{{ register_docker_compose_version.stdout_lines }}"