---
- name: Ensure group {{ redis_exporter_user }} exists
  group:
    name: "{{ redis_exporter_user }}"
    state: present

- name: Add the user {{ redis_exporter_user }} in group {{ redis_exporter_user }}
  user:
    name: "{{ redis_exporter_user }}"
    shell: /sbin/nologin
    groups: 
      - "{{ redis_exporter_user }}"
    append: yes

- name: Unarchive node_exporter
  unarchive:
    src: "{{ redis_exporter_package }}"
    dest: /usr/local/bin
    extra_opts:
      - --strip-components=1
    remote_src: yes

