---
- name: Config /etc/security/limits.conf
  template:
    src: etc/security/limits.conf.j2
    dest: /etc/security/limits.conf

- name: Interim executive
  shell: |
    ulimit -n 65536
  args:
    warn: no