---
- name: Yum install td-agent
  yum:
    name: "{{ td_agent_uri }}"
    state: present
    update_cache: true

- name: Gem install td-agent plugins
  shell: |
    td-agent-gem install {{ item }}
  args:
    warn: no
  loop: "{{ td_agent_gem_plugins }}"

