---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install nginx
  yum:
    name: nginx
    state: latest

- name: Restart nginx
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: nginx